name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10.13.1
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
